import React from "react";

const PrivacyPolicy = () => {
  return (
    <div className="mx-auto px-4 py-12 text-gray-800">
      <h1 className="text-3xl font-bold mb-2">PRIVACY POLICY — NeighborConnector™</h1>
      <p className="text-sm text-gray-600 mb-8">Effective Date: January 1, 2025</p>

      <p className="mb-6">
        Community Care Housing ("Community Care Housing," "CCH," "we," "us," or "our") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, store, share and protect personal information when you use the NeighborConnector™ mobile application ("the App").
      </p>

      <p className="mb-6">
        NeighborConnector™ is operated by Community Care Housing, a United States–based 501(c)(3) nonprofit organization headquartered in Colorado.
      </p>

      <p className="mb-6">
        This Privacy Policy applies only to NeighborConnector™ and does not apply to third-party websites, services or applications.
      </p>

      <p className="mb-8 font-semibold">
        Please read this Privacy Policy before accessing or using the App. By using or continuing to use the App, you acknowledge and agree to the practices described in this Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">1. Information We Collect</h2>
      <p className="mb-4">We collect only the information reasonably necessary to operate the App and provide its core features.</p>

      <h3 className="text-lg font-semibold mt-6 mb-3">1.1 Information You Provide Directly</h3>
      <p className="mb-3">When you create an account or use the App, at your discretion you may provide:</p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>Full name</li>
        <li>Email address</li>
        <li>Cell phone number</li>
        <li>Home address (house number and street name only)</li>
        <li>Emergency contact information (names, phone numbers, and relationship) – Visibility within the App will be optional</li>
        <li>Weekly schedule information for this App only (for optional responses to postings)</li>
        <li>Messages, group interactions and other communications</li>
        <li>User-generated content, such as text or images you choose to upload</li>
      </ul>
      <p className="mb-6">Providing sensitive information (such as personal information including health-related or other personal circumstances) is entirely voluntary and is not required to use the App's core functionality.</p>

      <h3 className="text-lg font-semibold mt-6 mb-3">1.2 Information Collected Automatically</h3>
      <p className="mb-3">When you use the App, we may automatically collect limited technical information in relation to the App, including:</p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>Device type and operating system</li>
        <li>By using Cookies, app usage logs and diagnostics</li>
        <li>Unique device or user identifiers generated by Firebase</li>
        <li>No GPS Tracking: NeighborConnector™ does not automatically collect or track precise location data.</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-10 mb-4">2. How We Use Your Information</h2>
      <p className="mb-3">We use the information we collect to:</p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>Create and manage user accounts</li>
        <li>Enable messaging, group communication and community features</li>
        <li>Display and manage emergency contacts</li>
        <li>Facilitate optional safety check-ins</li>
        <li>Send essential service notifications (email or SMS)</li>
        <li>Maintain App security and prevent misuse</li>
        <li>Improve App functionality, performance and reliability</li>
        <li>Support nonprofit operations, including community outreach, education and program awareness</li>
      </ul>
      <p className="mb-6">We do not sell personal information and do not use personal data for advertising or marketing by third parties.</p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">3. Sharing of Information</h2>
      <p className="mb-6">We share personal information only as described below.</p>

      <h3 className="text-lg font-semibold mt-6 mb-3">3.1 Service Providers</h3>
      <p className="mb-3">We use trusted third-party service providers solely to operate and support the App, including:</p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>Firebase (Google): authentication, notifications, database services</li>
        <li>Amazon Web Services (AWS): secure data hosting and storage</li>
        <li>Twilio: SMS service notifications</li>
      </ul>
      <p className="mb-6">These providers process personal information only on our behalf and subject to confidentiality and security obligations.</p>

      <h3 className="text-lg font-semibold mt-6 mb-3">3.2 Legal and Safety Obligations</h3>
      <p className="mb-3">We may disclose information if required to do so by law or if we believe disclosure is necessary to:</p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>Comply with legal obligations or lawful requests</li>
        <li>Protect the safety, rights or property of users or others</li>
        <li>Prevent fraud, abuse or security threats</li>
      </ul>

      <h3 className="text-lg font-semibold mt-6 mb-3">3.3 User-Directed Sharing</h3>
      <p className="mb-6">Information may be shared with emergency contacts or other users only when you choose to do so through the App's features.</p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">4. Donations & Payment Information</h2>
      <p className="mb-3">NeighborConnector™ is provided at no cost to users. Community Care Housing may offer users the opportunity to make voluntary donations to support app maintenance, community outreach, education and awareness efforts.</p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>Donations are optional and are not required to use the App</li>
        <li>Donations do not unlock features, provide enhanced services or affect how the App functions</li>
        <li>Payment information, if collected, is processed by third-party payment processors and is not stored by Community Care Housing or its servers or within the App.</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-10 mb-4">5. Data Retention</h2>
      <p className="mb-3">We retain personal information:</p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>For as long as your account remains active</li>
        <li>As necessary to provide App services</li>
        <li>To comply with legal, regulatory or safety obligations</li>
        <li>For internal security, audit and integrity purposes</li>
      </ul>
      <p className="mb-6">When personal information is no longer required, we delete or de-identify it in accordance with applicable law. Backup copies may persist for a limited time for system reliability and security.</p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">6. Security Measures</h2>
      <p className="mb-3">We implement reasonable technical and organizational safeguards designed to protect personal information, including:</p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>Encryption of data in transit and at rest</li>
        <li>Restricted access to authorized personnel only</li>
        <li>Secure infrastructure provided by Firebase and AWS</li>
      </ul>
      <p className="mb-6">While we take data protection seriously, no system or method of transmission is completely secure, and we cannot guarantee absolute security.</p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">7. Your Rights and Choices</h2>
      <p className="mb-3">Depending on your jurisdiction, you may have the right to:</p>
      <ul className="list-disc list-inside mb-6 space-y-2">
        <li>Request access to your personal information</li>
        <li>Request correction or deletion of your information</li>
        <li>Withdraw consent where processing is based on consent</li>
        <li>Opt out of non-essential communications</li>
      </ul>
      <p className="mb-6">Requests may be submitted by contacting us at: <a href="mailto:info@communitycarehousing.org" className="text-blue-600 hover:underline">📩 info@communitycarehousing.org</a></p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">8. Children's Privacy</h2>
      <p className="mb-6">NeighborConnector™ is intended for users 13 years of age or older. We do not knowingly collect personal information from children under 13. If we learn that such information has been collected, we will delete it promptly.</p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">9. Changes to This Privacy Policy</h2>
      <p className="mb-6">We may update this Privacy Policy from time to time. When we do, we will revise the "Effective Date" and post the updated policy in the App or on our website. Continued use of the App after changes become effective indicates acceptance of the updated policy.</p>

      <h2 className="text-2xl font-semibold mt-10 mb-4">10. Contact Information</h2>
      <p className="mb-2">If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact:</p>
      <p className="mb-6">
        <a href="mailto:info@communitycarehousing.org" className="text-blue-600 hover:underline">info@communitycarehousing.org</a>
      </p>
      <p className="text-gray-700">
        Community Care Housing<br />
        Colorado, United States<br />
        501(c)(3) nonprofit organization
      </p>
    </div>
  );
};

export default PrivacyPolicy;
